development:
  adapter: postgresql
  encoding: utf8
  database: unasuke_quotes_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: unasuke_quotes_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: unasuke_quotes_production
  pool: 5
  username:
  password:
